// This file is auto-generated by scripts/generate-property-metadata.ts
// Do not edit manually

import { registerGeneratedPropertyMetadata } from '@gnsx/genesys.js';


export function registerMetadata(): void {
}

// Deferred to avoid circular reference issues during module initialization
queueMicrotask(registerMetadata);
