// This file is auto-generated by scripts/generate-property-metadata.ts
// Do not edit manually

import { registerGeneratedPropertyMetadata } from '@gnsx/genesys.js';

import { IsometricPlayerPawn } from './actors/IsometricPlayerPawn.js';
import { ZombieActor } from './actors/ZombieActor.js';
import { IsometricMovementComponent } from './components/movement/IsometricMovementComponent.js';

export function registerMetadata(): void {
  registerGeneratedPropertyMetadata(IsometricPlayerPawn, {
      "cameraDistance": {
        "type": "number",
        "min": 5,
        "max": 80,
        "step": 1,
        "category": "Camera"
      },
      "visualGroundClearance": {
        "type": "number",
        "min": -1,
        "max": 2,
        "step": 0.001,
        "category": "Visual"
      }
    });

  registerGeneratedPropertyMetadata(ZombieActor, {
      "maxHealth": {
        "type": "number",
        "min": 1,
        "max": 5000,
        "step": 1,
        "category": "Zombie"
      },
      "moveSpeed": {
        "type": "number",
        "min": 0.5,
        "max": 20,
        "step": 0.1,
        "category": "Zombie"
      },
      "aggroRadius": {
        "type": "number",
        "min": 1,
        "max": 100,
        "step": 0.5,
        "category": "Zombie"
      },
      "attackRange": {
        "type": "number",
        "min": 0.3,
        "max": 5,
        "step": 0.05,
        "category": "Zombie"
      },
      "attackDamage": {
        "type": "number",
        "min": 0,
        "max": 500,
        "step": 1,
        "category": "Zombie"
      },
      "attackCooldown": {
        "type": "number",
        "min": 0.1,
        "max": 10,
        "step": 0.1,
        "category": "Zombie"
      },
      "deathLaunchForce": {
        "type": "number",
        "min": 0,
        "max": 30,
        "step": 0.5,
        "category": "Zombie"
      },
      "wanderRadius": {
        "type": "number",
        "min": 2,
        "max": 50,
        "step": 0.5,
        "category": "Zombie"
      },
      "wanderWaitMin": {
        "type": "number",
        "min": 0.5,
        "max": 20,
        "step": 0.5,
        "category": "Zombie"
      },
      "wanderWaitMax": {
        "type": "number",
        "min": 0.5,
        "max": 30,
        "step": 0.5,
        "category": "Zombie"
      }
    });

  registerGeneratedPropertyMetadata(IsometricMovementComponent, {
      "lookRightSpeed": {
        "type": "number",
        "hidden": true
      },
      "lookUpSpeed": {
        "type": "number",
        "hidden": true
      },
      "jumpSpeed": {
        "type": "number",
        "hidden": true
      },
      "maxMidAirJumps": {
        "type": "number",
        "hidden": true
      },
      "midAirAccelerationLambda": {
        "type": "number",
        "hidden": true
      },
      "midAirDecelerationLambda": {
        "type": "number",
        "hidden": true
      },
      "jumpStrengthModifier": {
        "type": "number",
        "hidden": true
      },
      "characterControllerOptions": {
        "type": "object",
        "fields": {
          "offset": {
            "type": "number"
          },
          "simulatedGravityScale": {
            "type": "number"
          },
          "applyImpulsesToDynamicBodies": {
            "type": "boolean"
          },
          "characterMass": {
            "type": "number"
          },
          "slideEnabled": {
            "type": "boolean"
          },
          "maxSlopeClimbAngle": {
            "type": "number"
          },
          "minSlopeSlideAngle": {
            "type": "number"
          },
          "snapToGroundDistance": {
            "type": "number"
          },
          "autoStepConfig": {
            "type": "object",
            "fields": {
              "maxHeight": {
                "type": "number"
              },
              "minWidth": {
                "type": "number"
              },
              "includeDynamicBodies": {
                "type": "boolean"
              }
            }
          }
        },
        "hidden": true
      }
    });

}

// Deferred to avoid circular reference issues during module initialization
queueMicrotask(registerMetadata);
